apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: abhitrone/grafana-backup:04
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/src"
          name: task-pv-storage



