
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-all-deployment
spec:
  selector:
    matchLabels:
      app: django
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: abhitrone/django_prometheus:testingWebhook
        ports:
        - name: djangoport
          containerPort: 8000
        env:
        - name: HOST_IP
          value: 192.168.64.3
---
apiVersion: v1
kind: Service
metadata:
  name: django-all-service
  labels: 
    app: django
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "30486" #dont know whats use of this
spec:
  type: LoadBalancer
  selector:
    app: django
  ports:
  - name: djangoport
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32104 #custom pod port, so that i can use this port below in service monitor
  selector:
    app: django

---
# service-monitor.yml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: demo-django
      #release: prometheus
      #prometheus: prometheus
  name: django
  namespace: grafana-test
spec:
  endpoints:
    - path: /metrics
    - scrapeTimeout: "10s" #for the error execution time out in targets
    - port: djangoport
      #relabelings:
      # - targetLabel: "__address__"
      #   replacement: "192.168.64.3:32304" #host_pod_ip and custom  nodePort 
  namespaceSelector:
    matchNames:
      - grafana-test
  selector:
    matchLabels:
      app: django
        #instance: django


---
#run django_alert.yaml to add new rules and create alerts. 
#kubectl apply -f django_alert.yaml
